added support for downloading qcow images from rhsm

diff --git a/roles/proxmox-templates/tasks/main.yml b/roles/proxmox-templates/tasks/main.yml
--- a/roles/proxmox-templates/tasks/main.yml
+++ b/roles/proxmox-templates/tasks/main.yml
@@ -7,36 +7,55 @@
     group: root
     mode: 0755
 
-# We can inject code here to grab the qcow images via rhsm
-# We need the rhsm_token, image_checksum
-#
-# token=`curl -s https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token -d grant_type=refresh_token -d client_id=rhsm-api -d refresh_token=$offline_token | jsonValue access_token`
-# img=`curl -s -H "Authorization: Bearer $token"  "https://api.access.redhat.com/management/v1/images/${image_sha}/download | jq -r '.body.href'"`
-# curl $url -o test.iso
+- name: Download the qcow images from rhsm
+  shell: |
+    set -e
+    img_path="{{ proxmox_template_qcow_storage_dir }}/{{ item.value.image }}"
 
-- name: Get rhsm token
-  uri:
-    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
-    method: POST
-    body:
-      grant_type: refresh_token
-      client_id: rhsm-api
-      refresh_token: "{{ rhsm_token }}"
-  register: __rhsm_token
+    sha=$(sha256sum ${img_path} | awk '{print $1}')
 
+    if [ "${sha}" == "{{ item.value.sha_checksum }}" ]; then
+      exit 1
+    fi
 
+    token=$(curl -s https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token \
+      -d grant_type=refresh_token \
+      -d client_id=rhsm-api \
+      -d refresh_token=${RHSM_TOKEN} | jq -r '.access_token')
 
-- name: Upload cloud images from rhsm
+    img=$(curl -s -H "Authorization: Bearer ${token}" "https://api.access.redhat.com/management/v1/images/{{ item.value.sha_checksum }}/download")
 
-- name: Upload cloud images from local
-  copy:
-    src: "{{ item.value.src_dir }}/{{ item.value.image }}"
-    dest: "{{ proxmox_template_qcow_storage_dir }}/{{ item.value.image }}"
-    owner: root
-    group: root
-    mode: 0644
+    if [ "${img}" == "Authentication required" ]; then
+      echo "Authentication failed"
+      exit 2
+    fi
+
+    url=$(echo ${img} | jq -r '.body.href')
+    if [ "$?" != "0" ]; then
+      echo ${url}
+      exit 2
+    fi
+    curl -s ${url} -o "${img_path}"
+  args:
+    executable: /bin/bash
+  environment:
+    RHSM_TOKEN: "{{ rhsm_token }}"
+  failed_when: __qcow_debug.rc > 1
+  changed_when: __qcow_debug.rc != 1
+  register: __qcow_debug
   loop: "{{ proxmox_templates | dict2items }}"
-  when: (rhsm_token is not defined) and (rhsm_token|length == 0)
+  when: (rhsm_token is defined) and (rhsm_token|length > 0)
+
+# Deprecated by the task above - now we can download the qcow images directly from rhsm rather than staging them locally
+#- name: Upload cloud images from local
+#  copy:
+#    src: "{{ item.value.src_dir }}/{{ item.value.image }}"
+#    dest: "{{ proxmox_template_qcow_storage_dir }}/{{ item.value.image }}"
+#    owner: root
+#    group: root
+#    mode: 0644
+#  loop: "{{ proxmox_templates | dict2items }}"
+#  when: (rhsm_token is not defined) and (rhsm_token|length == 0)
 
 - name: Create template VMs
   proxmox_kvm:
